apiVersion: v1
kind: Service
metadata:
  name: zook-svc
  namespace: adtd-kafka
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: zookeeper-port
    targetPort: 2181
    protocol: TCP
  selector:
    app: zookeeper