apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-controller
  namespace: adtd-kafka
spec:
  replicas: 1
  selector:
    app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zook-svc.adtd-kafka:2181
        - name: KAFKA_CREATE_TOPICS
          value: "system.events:1:1"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx150M -Xms50M"
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
          requests:
            cpu: 300m
            memory: 400Mi